#!/bin/bash

# Print current directory for debugging
echo "Post-clone script: Current directory: $(pwd)"

# Create local.properties if it doesn't exist
if [ ! -f "./android/local.properties" ]; then
  echo "Creating android/local.properties file..."
  mkdir -p android
  cat > android/local.properties << 'EOL'
# This file is automatically generated by EAS Build.
sdk.dir=/opt/android/sdk
ndk.dir=/opt/android/sdk/ndk
compileSdkVersion=34
targetSdkVersion=34
minSdkVersion=24
buildToolsVersion=35.0.0
EOL
  echo "android/local.properties created successfully"
else
  echo "android/local.properties already exists"
fi

echo "Post-clone script completed" 