#!/bin/bash

# Print current directory for debugging
echo "Current directory: $(pwd)"

# Check for the android directory
if [ -d "android" ]; then
  cd android
  echo "Changed to android directory: $(pwd)"
else
  echo "Android directory not found, creating it"
  mkdir -p android
  cd android
  echo "Created and changed to android directory: $(pwd)"
fi

# Create gradlew file if it doesn't exist
if [ ! -f "./gradlew" ]; then
  echo "gradlew not found, creating it..."
  
  # Create minimal gradlew script
  cat > gradlew << 'EOL'
#!/bin/sh
# Gradle start up script
# Auto-generated by EAS build

# Determine the JVM command to use
if [ -n "$JAVA_HOME" ]; then
  JAVACMD="$JAVA_HOME/bin/java"
else
  JAVACMD="java"
fi

# Use the wrapper jar file
APP_HOME=`pwd`
JAR_PATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ -e "$JAR_PATH" ]; then
  # Execute Gradle
  exec "$JAVACMD" -jar "$JAR_PATH" "$@"
else
  echo "Gradle wrapper JAR file not found: $JAR_PATH"
  echo "This is most likely because your Android project was not properly initialized."
  echo "Attempting to continue by executing 'gradle' directly..."
  
  # Try to use gradle directly as fallback
  if command -v gradle &> /dev/null; then
    exec gradle "$@"
  else
    echo "Error: Gradle is not installed or not in the PATH."
    exit 1
  fi
fi
EOL

  # Make it executable
  chmod +x gradlew
  echo "Created and made gradlew executable"
else
  echo "gradlew already exists, making it executable"
  chmod +x gradlew
fi

# Create gradle directory structure if it doesn't exist
if [ ! -d "gradle/wrapper" ]; then
  echo "Creating gradle wrapper directory structure"
  mkdir -p gradle/wrapper
  
  # Create basic gradle-wrapper.properties
  cat > gradle/wrapper/gradle-wrapper.properties << 'EOL'
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
EOL
  
  echo "Created gradle wrapper properties file"
fi

# Check if gradle-wrapper.jar exists
if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
  echo "Downloading gradle-wrapper.jar..."
  
  # Use curl to download the jar file (most build environments have curl)
  if command -v curl &> /dev/null; then
    curl -s -o gradle/wrapper/gradle-wrapper.jar "https://github.com/gradle/gradle/raw/master/gradle/wrapper/gradle-wrapper.jar"
    echo "Downloaded gradle-wrapper.jar"
  else
    echo "Warning: Could not download gradle-wrapper.jar, curl not available"
  fi
fi

echo "Gradle setup completed"

# Return to the original directory
cd .. 